### ISSUE TITLE
How to clear console screen

### ISSUE THREAD

**Issue by liyuanrui** [chaquo/chaquopy-console#1]
hello, I can't find any way to clear console screen, can somebody help? thanks

it can't clear console screen.
```
import sys
def main():
    write,flush=sys.stdout.write,sys.stdout.flush
    for i in range(10):
        time.sleep(0.5)
        ctime=time.ctime()[11:19]
        write(ctime)
        flush()
        write('\x08'*len(ctime))
    print('Hello World')
```

**Comment by mhsmith** [comment]
The console doesn't currently support using backspace or carriage return to modify text already written. A pull request adding this feature would be welcome.

**Comment by liyuanrui** [comment]
It‘s hoped that a clear interface will be made

**Comment by mhsmith** [comment]
> Now I use chaquo-console to develop a weather forecast app(https://www.coolapk.com/apk/186327). It's fast and I like it very much. Thanks to your chaquopy project. Well, there is a problem. I don't know how to get the current activity and R.ids.tvOutput in main.py. , I want setText='' to achieve a clear screen effect

You can easily pass objects between Java and Python using function calls or PyObject.get/put. However, it would be better not to pass references to the activity and the text box, because Android recreates them every time you rotate the screen. This is part of the reason why the Java code for the console is so complex.

Perhaps the easiest way to do what you want would be to use a special character. For example, in Unix ^L is sometimes used as a "clear screen" character. You could simply print("\x0c") in Python, and then modify ConsoleActivity.output to detect this character and clear the text box.

You could generalize this by creating your own "escape sequences" to instruct the Java code to do anything you want.

**Comment by liyuanrui** [comment]
Well, I realized, thanks
